### ISSUE TITLE
Implementação da entidade Responsável e de suas camadas

### ISSUE THREAD

**Issue by GabrielFerreiraSilva** [GabrielFerreiraSilva/temporario#1]
## Descrição

Esta issue visa a implementação da entidade Responsável, que modela, no sistema, os responsáveis pelas crianças que realizam atividades. Além disso, visa a implementação das classes que atuam na camada Controller, Service e Repository para essa entidade. Com isso, a interação com a View, a lógica de negócios e a persistência dos dados podem ser garantidas para a entidade Responsável.

## Arquivos

Crie e configure os seguintes arquivos, em seus respectivos pactotes:

- model/Responsavel.java
- repository/ResponsavelRepository.java
- service/ResponsavelService.java
- controller/ResponsavelController.java

## Tasks

- [ ] Criar e configurar a classe Responsavel.java
- [ ] Criar e configurar a classe ResponsavelRepository.java
- [ ] Criar e configurar a classe ResponsavelService.java
- [ ] Criar e configurar a classe ResponsavelController.java
