### ISSUE TITLE
Implementação de autenticação e autorização no sistema

### ISSUE THREAD

**Issue by GabrielFerreiraSilva** [GabrielFerreiraSilva/temporario#2]
## Descrição

Esta issue visa a implementação de um serviço de autenticação e autorização no sistema. Utilizando o framework Spring Security e o esquema de autenticação Basic Auth, a implementação deve assegurar que os usuário tenham acesso apenas às funcionalidades correspondentes ao seu papel no sistema.

## Arquivos

Crie e configure os seguintes arquivos, em seus respectivos pactotes. Além disso, crie qualquer outro arquivo que seja necessário para a completa implementação da funcionalidade.

- controller/AutenticacaoController.java
- config/SecurityConfig.java
- security/AutenticacaoFilter.java
- service/AutenticacaoService.java

## Tasks

- [ ] Adicionar a dependência do Spring Security ao pom.xml
- [ ] Criar e configurar a classe AutenticacaoController.java
- [ ] Criar e configurar a classe SecurityConfig.java
- [ ] Criar e configurar a classe AutenticacaoFilter.java
- [ ] Criar e configurar a classe AutenticacaoService.java
